### ISSUE TITLE
第二天就用不了了

### ISSUE THREAD

**Issue by ICE99125** [TencentCloudBase-Marketplace/bitwarden#11]
密码错误
![image](https://user-images.githubusercontent.com/65435402/115959882-0927e980-a541-11eb-9f55-08243e2106cd.png)
新注册也错误
![image](https://user-images.githubusercontent.com/65435402/115959904-28267b80-a541-11eb-9dcd-db433880bd2a.png)

**Comment by l2021v** [comment]
一样的问题，突然就失效了。

**Comment by ATIAboo** [comment]
提交工单了，要重新部署，开通的时候加个数据库才行。但是数据库实在是太贵了，我冲了五块钱没两三天就用完了。

**Comment by ICE99125** [comment]
我改用其他的了，主要是不太会用云开发，出问题了也不知道该买哪个服务

**Comment by binggg** [comment]
README 文档里升级了下，提供了两种部署方式

MySQL 部署（MySQL + CFS文件存储）

SQLite 部署（CFS文件存储）
