### ISSUE TITLE
cfs支持问题

### ISSUE THREAD

**Issue by MusherM** [TencentCloudBase-Marketplace/bitwarden#12]
我在腾讯云部署的这个应用，突然有一天就登陆不上去了，服务器提供商说是你们后台改了接口，不再支持cfs了
请问我的数据怎么办，这么大的改动为什么也不提前通知呢

**Comment by binggg** [comment]
你好，不好意思这里当时切换部署方式是因为发现单独使用CFS存在一些问题，切换到了数据库版本

请问现在可以重现登录不了的问题么？

**Comment by MusherM** [comment]
实在太折磨了，一边是服务器提供商一边是开源社区，一堆密码存在里面拿不出来，中间还被服务商宰了一刀
后来倒是在ios版本上估计是因为bug成功使用指纹登录把数据导出来了，现在在用官方的服务
直到大概一天前，还是登录不上去的，提示还是用户名或密码错误



---原始邮件---
发件人: "Booker ***@***.***&gt;
发送时间: 2021年5月7日(周五) 下午4:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentCloudBase-Marketplace/bitwarden] cfs支持问题 (#12)




 
你好，不好意思这里当时切换部署方式是因为发现单独使用CFS存在一些问题，切换到了数据库版本
 
请问现在可以重现登录不了的问题么？

**Comment by binggg** [comment]
现在服务还在么

**Comment by MusherM** [comment]
服务器已经欠费停机了，不过我这边有腾讯云客服的联系方式，他们说他们已经在排查了，说来奇怪，他们排查问题不联系你们的吗
你需要联系方式我可以给你，你们对接一下好了



---原始邮件---
发件人: "Booker ***@***.***&gt;
发送时间: 2021年5月7日(周五) 下午4:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [TencentCloudBase-Marketplace/bitwarden] cfs支持问题 (#12)




 
现在服务还在么

**Comment by binggg** [comment]
OK，我们内部对接下，因为不太确定社区收到的反馈和工单是不是同一个
