### ISSUE TITLE
部署好后（可正常使用），导入数据出错

### ISSUE THREAD

**Issue by eallion** [TencentCloudBase-Marketplace/bitwarden#2]
部署好后（可正常使用），导入数据出错。
![Snipaste_2020-12-03_19-44-42](https://user-images.githubusercontent.com/1698841/101014177-675b2c80-35a0-11eb-9c98-f2bef452bfc4.png)

**Comment by chhpt** [comment]
这个是超时错误，请求时间过长会出现这种错误

**Comment by eallion** [comment]
> 这个是超时错误，请求时间过长会出现这种错误

字我都认识啊。

**Comment by binggg** [comment]
@eallion 导入的数据大小是怎样的

**Comment by eallion** [comment]
![Snipaste_2020-12-04_17-23-43](https://user-images.githubusercontent.com/1698841/101146029-7d76f480-3655-11eb-99f0-deac25b24497.png)
![Snipaste_2020-12-04_17-20-19](https://user-images.githubusercontent.com/1698841/101146019-794ad700-3655-11eb-8404-577a0e4fe88d.png)

**Comment by binggg** [comment]
这么小，我们也重现下

**Comment by eallion** [comment]
> 这么小，我们也重现下

这是从我在用的自建账号中导出的。我在本地拉了个镜像试了下，可以导入。

**Comment by binggg** [comment]
好的

**Comment by eallion** [comment]
今天重试了一下，偶尔会导入数据，但只能导入部分数据，而且出现重复。

**Comment by zhaogarvie** [comment]
遇到了相同的问题+1，而且导入出错之后也无法清空密码库，然后就直接卡死被强行退出登录卡在登录页面了

**Comment by dingtwo** [comment]
同样的问题，看日志是：database is locked
![image](https://user-images.githubusercontent.com/11864117/112277536-d4fca700-8cbc-11eb-9b39-08f51c6fceb5.png)

**Comment by dingtwo** [comment]
> 同样的问题，看日志是：database is locked
> ![image](https://user-images.githubusercontent.com/11864117/112277536-d4fca700-8cbc-11eb-9b39-08f51c6fceb5.png)

自己回答，应该是第一次导入导致 sqlite锁了并且哦返回超时，后面再导入会一直失败，等了一会儿好了

**Comment by wasdjkl** [comment]
遇到了相同的问题，只能导入部分数据，且每条数据重复出现三次

**Comment by glsname** [comment]
同样的问题 希望能尽快处理一下。

**Comment by dingtwo** [comment]
感觉是 sqllite 性能导致的，db 能否做成参数选择

**Comment by binggg** [comment]
目前最新的master分支用的是mysql，如果全新安装的话可以用这个

**Comment by binggg** [comment]
README 文档里升级了下，提供了两种部署方式

MySQL 部署（MySQL + CFS文件存储）

SQLite 部署（CFS文件存储）
