### ISSUE TITLE
无法覆盖默认的 SIGNUPS_ALLOWED 环境变量

### ISSUE THREAD

**Issue by ghost** [TencentCloudBase-Marketplace/bitwarden#4]
我在 “我的应用-管理-环境变量” 里面写入了SIGNUPS_ALLOWED:false，但在云托管一侧的环境变量里依然是 SIGNUPS_ALLOWED:true。

由于bitwardenrs默认的SIGNUPS_ALLOWED是true，我建议把cloudbaserc.json配置文件里的这个值移除。可能是cloudbaserc.json的优先级更高？

**Comment by chhpt** [comment]
@uuznn 你可以尝试以下办法
1. 云托管中尝试修改环境并重新部署，如果是从我的应用中部署，会覆盖编辑的变量。
2. fork 本仓库，自行修改部署

仓库中的 SIGNUPS_ALLOWED 不会移除，否则会造成首次部署后无法登录

**Comment by uuznn** [comment]
> @uuznn 你可以尝试以下办法
> 
> 1. 云托管中尝试修改环境并重新部署，如果是从我的应用中部署，会覆盖编辑的变量。
> 2. fork 本仓库，自行修改部署
> 
> 仓库中的 SIGNUPS_ALLOWED 不会移除，否则会造成首次部署后无法登录

bitwarders 的 SIGNUPS_ALLOWED 默认为 true。就算不通过环境变量明示，依然开放注册

**Comment by chhpt** [comment]
@uuznn 好的，我们把这个变量去掉
