### ISSUE TITLE
可不可以上传数据库文件到CloudBase的应用目录？

### ISSUE THREAD

**Issue by Aquaakuma** [TencentCloudBase-Marketplace/bitwarden#5]
在别的服务器部署了bitwarden，想把数据库文件备份复制的CloudBase上的bitwarden上，因为bitwarden的数据导出成csv格式的不能包括TOTP和附件，能在CLoudBase上进行文件操作比较好。

**Comment by uuznn** [comment]
他们这个是把数据存在CFS里面的。因此你可以临时启动一个CVM并挂载CFS，然后把数据拖放上去覆盖。

**Comment by chhpt** [comment]
@TUT123456 可以尝试通过 WebShell 登录，从云存储中下载文件进行覆盖
