### ISSUE TITLE
一健部署反复失败，请求帮助QAQ 谢谢

### ISSUE THREAD

**Issue by iPixelOldC** [TencentCloudBase-Marketplace/bitwarden#6]
日志如下，不断重复：

> bitwarden-001 2021-03-05T15:13:45.46753985Z stdout F [INFO] No .env file found.
> bitwarden-001 2021-03-05T15:13:45.467542444Z stdout F
> bitwarden-001 2021-03-05T15:13:45.523802679Z stdout F [2021-03-05 15:13:45.523][bitwarden_rs::util][WARN] Can't connect to database, retrying: DieselMigError.
> bitwarden-001 2021-03-05T15:13:45.523845023Z stdout F [CAUSE] QueryError(
> bitwarden-001 2021-03-05T15:13:45.523893126Z stdout F DatabaseError(
> bitwarden-001 2021-03-05T15:13:45.523923395Z stdout F __Unknown,
> bitwarden-001 2021-03-05T15:13:45.523960129Z stdout F "no such table: __diesel_schema_migrations",
> bitwarden-001 2021-03-05T15:13:45.523997864Z stdout F ),
> bitwarden-001 2021-03-05T15:13:45.524025294Z stdout F )

**Comment by iPixelOldC** [comment]
我谷歌了下相关内容，貌似有人用azure时也出现了问题，但他说不是bw的问题，是azure的设置问题，这个一键部署，是还需要勾选什么选项吗？我是新开通的用户，反正要我勾的我都勾了。

**Comment by binggg** [comment]
环境id 给下

**Comment by iPixelOldC** [comment]
原来的那个环境我删了，刚刚创建了个新的，环境ID：test-2gmj0dpx40d02231
但这个新的也一样无法启动，且云托管日志里的报错也是一样的。

**Comment by iPixelOldC** [comment]
突然可以了，不知道为啥。。。谢谢了
