### ISSUE TITLE
很久才能登入一次，登录后经常同步不到数据，然后自动退出，一直无法登入。要过非常久才能登入，无限循环

### ISSUE THREAD

**Issue by skiqing** [TencentCloudBase-Marketplace/bitwarden#8]
{"@filepath":"/var/log/eks-log-agent/default_bitwarden-001-66797b54b6-h459m_23fbf1ac-8bd1-11eb-8087-e6dca839163d/containers/bitwarden-001/stdout/1.log","container_name":"bitwarden-001","log":"2021-03-26T09:49:26.985952505Z stdout F [2021-03-26 09:49:26.985][response][INFO] GET /api/sync?<data..> (sync) => 200 OK","tcb_type":"CloudBaseRun"}
![QQ截图20210326175746](https://user-images.githubusercontent.com/40341618/112614959-da90f300-8e5c-11eb-9856-1bdd738c395f.png)

**Comment by cayzlh** [comment]
同
