### ISSUE TITLE
部署之后貌似极其不稳定，出现各种错误

### ISSUE THREAD

**Issue by cayzlh** [TencentCloudBase-Marketplace/bitwarden#9]
出现各种错误：

- 会话过期
- error saving device
  
<img width="317" alt="image" src="https://user-images.githubusercontent.com/12791269/112719093-e69ab480-8f31-11eb-9612-024470dfc76c.png">

- 发生意外错误

<img width="344" alt="image" src="https://user-images.githubusercontent.com/12791269/112719105-fdd9a200-8f31-11eb-9534-20f4075812d6.png">

还有各种问题。

期待修复。

**Comment by cayzlh** [comment]
补一个日志：

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/12791269/112719129-25c90580-8f32-11eb-9815-01b9e140a9cf.png">

**Comment by chhpt** [comment]
请尝试使用 service.tcloudbase.com 代替 app.tcloudbase.com  域名访问

**Comment by cayzlh** [comment]
> 请尝试使用 service.tcloudbase.com 代替 app.tcloudbase.com 域名访问

请教下具体在哪操作这个呢。 。

**Comment by binggg** [comment]
@cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试

**Comment by cayzlh** [comment]
> @cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试

我试试， 不过我是使用了自定义域名， 我按你说的来试试。

**Comment by cayzlh** [comment]
> @cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/12791269/113650360-aa4e1d80-96c2-11eb-972b-8add217ee5cd.png">

大佬， 还是一样。

**Comment by skiqing** [comment]
> 
> 
> @cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试

感谢，改了后很久没再掉了，怎么关闭其他用户注册，求大神告知怎么操作！

**Comment by cayzlh** [comment]
> @cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试

铲掉重新部署一遍就好了。

**Comment by cayzlh** [comment]
> > @cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试
> 
> 感谢，改了后很久没再掉了，怎么关闭其他用户注册，求大神告知怎么操作！

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/12791269/113832169-ed8bb780-97ba-11eb-9fe1-e4232282437b.png">

云托管里面找到你部署后的镜像，进去编辑后部署

**Comment by skiqing** [comment]
> 
> 
> > > @cayzlh 可以把控制台显示的访问域名里面的 app 改为 service 试试
> > 
> > 
> > 感谢，改了后很久没再掉了，怎么关闭其他用户注册，求大神告知怎么操作！
> 
> <img alt="image" width="1292" src="https://user-images.githubusercontent.com/12791269/113832169-ed8bb780-97ba-11eb-9fe1-e4232282437b.png">
> 
> 云托管里面找到你部署后的镜像，进去编辑后部署

可以了，Thanks♪(･ω･)ﾉ

**Comment by xiaodfeng** [comment]
你好，我遇到了类似的问题。即使将app更改为service，仍然无法登陆提示信息是username or password incorrect, please try again.

**Comment by cayzlh** [comment]
> 你好，我遇到了类似的问题。即使将app更改为service，仍然无法登陆提示信息是username or password incorrect, please try again.

这个提示是 用户名或密码错误 ， 你是不是记错密码了。

**Comment by xiaodfeng** [comment]
不是，我通过https://vault.bitwarden.com/是可以登录的。但是通过ap-shanghai.service.tcloudbase.com无法登陆

**Comment by skiqing** [comment]
> 不是，我通过[https://vault.bitwarden.com/是可以登录的。但是通过ap-shanghai.service.tcloudbase.com无法登陆](https://vault.bitwarden.com/%E6%98%AF%E5%8F%AF%E4%BB%A5%E7%99%BB%E5%BD%95%E7%9A%84%E3%80%82%E4%BD%86%E6%98%AF%E9%80%9A%E8%BF%87ap-shanghai.service.tcloudbase.com%E6%97%A0%E6%B3%95%E7%99%BB%E9%99%86)

重新部署一遍试试。

**Comment by xiaodfeng** [comment]
问题解决了，谢谢
